- name: Crear y arrancar contenedor 2048
  community.docker.docker_container:
    name: juego2048
    image: josedom24/2048:v1
    state: started
    restart_policy: unless-stopped
    published_ports:
      - "8080:80"
